baseURL: "https://asindu.xyz" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Asindu's Journal
theme: holy
publishDir: docs
googleAnalytics: G-S97K3JXL5P
disqusShortname: asindu

params:
  copyright: "© Asindu Willfred Drileba"

menu:
    main:
        - name: About
          url: /about
          weight: 3